# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_floating_object_part_dimensions_when_leaving_control.R

test_that("Doctest: logbook_floating_object_part_dimensions_when_leaving_control", {
  # Created from @doctest for `logbook_floating_object_part_dimensions_when_leaving_control`
  # Source file: R/logbook_floating_object_part_dimensions_when_leaving_control.R
  # Source line: 23
  dataframe1 <- data.frame(floatingobject_id = c("1", "2", "3", "4"),
  objectoperation_code = c("1", "8", "1", "1"))
  dataframe2 <- data.frame(floatingobjectpart_id = c("1", "2", "3", "4"),
  objectmaterial_code = c("1-1-1-1-6", "1-1-2-11", "1-1-1-1-7", "1-1"),
  floatingobjectpart_whenleaving = c("3", "5", "1", "true"), floatingobject_id = c(
    "1", "1", "3", "3"))
  expect_equal(logbook_floating_object_part_dimensions_when_leaving_control(
    dataframe1, dataframe2, output = "report"), structure(list(
    floatingobject_id = c("1", "2", "3", "4"), objectoperation_code = c("1",
      "8", "1", "1"), logical = c(TRUE, TRUE, FALSE, FALSE), count_objet_part = c(
      2, 0, 1, 0)), row.names = c(NA, -4L), class = "data.frame"))
})

