# Generated by doctest: do not edit by hand
# Please edit file in R/function_catch_or_sample_fate_unknown_control.R

test_that("Doctest: function_catch_or_sample_fate_unknown_control", {
  # Created from @doctest for `function_catch_or_sample_fate_unknown_control`
  # Source file: R/function_catch_or_sample_fate_unknown_control.R
  # Source line: 21
  catch <- data.frame(catch_id = c("1", "2", "3", "4"), speciesfate_code = c("4", "15", "9", "11"))
  expect_equal(function_catch_or_sample_fate_unknown_control(catch), structure(list(catch_id = c("1", "2", "3", "4"),
  speciesfate_code = c("4", "15", "9", "11"), logical = c(TRUE, TRUE, FALSE, FALSE)), class = "data.frame", row.names = c(
    NA, -4L)))
})

