# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_raising_factor_control.R

test_that("Doctest: logbook_raising_factor_control", {
  # Created from @doctest for `logbook_raising_factor_control`
  # Source file: R/logbook_raising_factor_control.R
  # Source line: 43
  dataframe1 <- data.frame(trip_id = c("1", "2", "3", "4", "5", "6", "7"))
  dataframe2 <- data.frame(catch_id = c("1", "2", "3", "4", "5", "6", "7", "8", "9"), catch_weight = c(10, 2, 15, 8, 5, 25, 4, 5, 9),
  speciesfate_code = c("6", "6", "1", "6", "6", "6", "6", "6", "6"), species_fao_code = c("TUN", "YFT", "TUN", "TUN", "TUN", "SKJ", "SKJ", "LOT",
    "BET"), vesselactivity_code = c("1", "1", "1", "1", "1", "1", "23", "1", "1"), trip_id = c("1", "1", "1", "2", "2", "3", "3", "3", "5"))
  dataframe3 <- data.frame(landing_id = c("1", "2", "3", "4", "5"), landing_weight = c(9, 2, 8, 25, 12), species_fao_code = c("YFT", "TUN", "TUN",
    "TUN", "BET"), trip_id = c("1", "1", "2", "4", "6"))
  dataframe4 <- data.frame(trip_id = c("1", "2", "3", "4", "5", "6", "7"), trip_end_full_trip_id = c("1", "2", "4", "4", "5", "6", "7"), vessel_id = c(
    "1", "1", "1", "1", "1", "1", "1"), country_fleetcountry = c("1", "1", "1", "1", "1", "1", "1"))
  expect_equal(logbook_raising_factor_control(dataframe1, dataframe2, dataframe3, dataframe4, output = "report"), structure(list(trip_id = c("1",
    "2", "3", "4", "5", "6", "7"), logical = c(TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE), rf1 = c(0.916666666666667, 0.615384615384615, 1, 1, NA,
    NA, NA)), row.names = c(NA, 7L), class = "data.frame"))
})

