# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_operationobjet_observedsystem_control.R

test_that("Doctest: logbook_operationobjet_observedsystem_control", {
  # Created from @doctest for `logbook_operationobjet_observedsystem_control`
  # Source file: R/logbook_operationobjet_observedsystem_control.R
  # Source line: 22
  dataframe1 <- data.frame(floatingobject_id = c("1", "2", "3", "4", "5"), objectoperation_code = c("1", "1", "2", "1", NA), activity_id = c("1", "2", "3", "3", "4"))
  dataframe2 <- data.frame(observedsystem_id = c("1", "2", "3"), observedsystem_code = c("1", "2", "20"), activity_id = c("1", "1", "3"))
  expect_equal(logbook_operationobjet_observedsystem_control(dataframe1, dataframe2, output = "report"), structure(list(floatingobject_id = c("1", "2", "3", "4", "5"),
  objectoperation_code = c("1", "1", "2", "1", NA), logical = c(TRUE, TRUE, TRUE, FALSE, FALSE), count_observed_system = c(0, 0, 1, 1, 0)), row.names = c(NA, 5L), class = "data.frame"))
})

