# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_weight_control.R

test_that("Doctest: logbook_weight_control", {
  # Created from @doctest for `logbook_weight_control`
  # Source file: R/logbook_weight_control.R
  # Source line: 22
  dataframe1 <- data.frame(activity_id = c("1", "2", "3", "4"), activity_weight = c(10, 15.01, 6, NA))
  dataframe2 <- data.frame(catch_id = c("1", "2", "3", "4", "5"), catch_weight = c(10, 10, 5, 3, 2), activity_id = c("1", "2", "2", "3", "3"))
  expect_equal(logbook_weight_control(dataframe1, dataframe2, output = "report"), structure(list(activity_id = c("1", "2", "3", "4"), logical = c(TRUE, TRUE,
    FALSE, TRUE), activity_weight = c(10, 15.01, 6, NA), sum_catch_weight = c(10, 15, 5, NA)), row.names = c(NA, 4L), class = "data.frame"))
})

