# Generated by doctest: do not edit by hand
# Please edit file in R/obs_sample_no_fate_control.R

test_that("Doctest: obs_sample_no_fate_control", {
  # Created from @doctest for `obs_sample_no_fate_control`
  # Source file: R/obs_sample_no_fate_control.R
  # Source line: 15
  sample <- data.frame(samplemeasure_id = c("1", "2", "3"), speciesfate_code = c(
    "6", "4", NA))
  expect_equal(obs_sample_no_fate_control(sample), structure(list(
    samplemeasure_id = c("1", "2", "3"), speciesfate_code = c("6", "4", NA),
    logical = c(TRUE, TRUE, FALSE)), class = "data.frame", row.names = c(NA,
    -3L)))
})

