# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_fishing_time_control.R

test_that("Doctest: logbook_fishing_time_control", {
  # Created from @doctest for `logbook_fishing_time_control`
  # Source file: R/logbook_fishing_time_control.R
  # Source line: 21
  dataframe1 <- data.frame(trip_id = c("1", "2", "3", "4", "5"), trip_fishingtime = c(10, 15, NA, 8, 0))
  dataframe2 <- data.frame(route_id = c("1", "2", "3", "4", "5", "6"), trip_id = c("1", "1", "2", "2", "3", "5"), route_fishingtime = c(4, 6, 10, 6, 14, 0))
  expect_equal(logbook_fishing_time_control(dataframe1, dataframe2, output = "report"), structure(list(trip_id = c("1", "2", "3", "4", "5"), logical = c(TRUE, FALSE,
    FALSE, FALSE, TRUE), trip_fishingtime = c(10, 15, NA, 8, 0), sum_route_fishingtime = c(10, 16, 14, NA, 0)), row.names = c(NA, -5L), class = "data.frame"))
})

