# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_activity_sample_control.R

test_that("Doctest: logbook_activity_sample_control", {
  # Created from @doctest for `logbook_activity_sample_control`
  # Source file: R/logbook_activity_sample_control.R
  # Source line: 19
  dataframe1 <- data.frame(sample_id = c("1", "2"))
  dataframe2 <- data.frame(sample_id = c("1"), activity_id = c("1"))
  expect_equal(logbook_activity_sample_control(dataframe1, dataframe2, output = "report"), structure(list(sample_id = c("1", "2"), logical = c(TRUE,
    FALSE)), row.names = c(NA, -2L), class = "data.frame"))
})

