# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_weighting_control.R

test_that("Doctest: logbook_weighting_control", {
  # Created from @doctest for `logbook_weighting_control`
  # Source file: R/logbook_weighting_control.R
  # Source line: 46
  dataframe1 <- data.frame(sample_id = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"),
  sample_smallsweight = c(10, 32, 2.5, 30, 12, 7, NA, 6, NA, 4, 8, 3, 7, 13, 54, 3, 8, 2, 16), sample_bigsweight = c(50, 2, 9, 3, 6, 13, 0, 3, 7, 2, 0, 2, 8, 3,
    62, 8, 15, 6, 1), sample_totalweight = c(NA, NA, NA, 33, 8, 9, 142, 2, 14, 10, 3, 0, NA, 0, 0, 104, 24, 36, 12), trip_id = c("1", "1", "2", "3", "4", "5", "6",
    "7", "8", "8", "8", "8", "8", "8", "1", "1", "1", "1", "1"), sampletype_code = c("1", "1", "1", "11", "11", "1", "1", NA, "1", "1", "1", "1", "1", "1", "1",
    NA, NA, NA, NA))
  dataframe2 <- data.frame(sampleactivity_id = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"),
  sampleactivity_weightedweight = c(70, 5, 18, 12, 33, 5, 9, 4, 13, 7, 4, 15, 116, 104, 24, 35, 11), sample_id = c("1", "1", "2", "3", "4", "5", "6", "8", "9",
    "11", "12", "14", "15", "16", "17", "18", "19"))
  dataframe3 <- data.frame(trip_id = c("1", "2", "3", "4", "6", "7", "8"), vesseltype_code = c("6", "6", "2", "2", "3", "2", "2"), vesseltype_label = c(
    "vessel_type_1", "vessel_type_1", "vessel_type_2", "vessel_type_2", "vessel_type_3", "vessel_type_2", "vessel_type_2"))
  dataframe4 <- data.frame(landing_id = c("1", "2", "3", "4", "5", "6"), landing_weight = c(85, 26, 30, 2.6, 20, 3), weightcategory_code = c("W-1", "W-1",
    "L-YFT-10", "L-YFT-10", "L-YFT-10", "L-BET-10"), trip_id = c("1", "2", "3", "3", "4", "7"))
  expect_equal(logbook_weighting_control(dataframe1, dataframe2, dataframe3, dataframe4, output = "report"), structure(list(sample_id = c("1", "2", "3", "4", "5",
    "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"), logical = c(TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE,
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE), sample_smallsweight = c(10, 32, 2.5, 30, 12, 7, NA, 6, NA, 4, 8, 3, 7, 13, 54, 3, 8, 2, 16),
  sample_bigsweight = c(50, 2, 9, 3, 6, 13, 0, 3, 7, 2, 0, 2, 8, 3, 62, 8, 15, 6, 1), sample_totalweight = c(NA, NA, NA, 33, 8, 9, 142, 2, 14, 10, 3, 0, NA, 0, 0,
    104, 24, 36, 12), sampletype_code = c("1", "1", "1", "11", "11", "1", "1", NA, "1", "1", "1", "1", "1", "1", "1", NA, NA, NA, NA), weightedweight = c(75, 18,
    12, 33, 5, 9, NA, 4, 13, NA, 7, 4, NA, 15, 116, 104, 24, 35, 11), vesseltype_label = c("vessel_type_1", "vessel_type_1", "vessel_type_1", "vessel_type_2",
    "vessel_type_2", NA, "vessel_type_3", "vessel_type_2", "vessel_type_2", "vessel_type_2", "vessel_type_2", "vessel_type_2", "vessel_type_2", "vessel_type_2",
    "vessel_type_1", "vessel_type_1", "vessel_type_1", "vessel_type_1", "vessel_type_1"), sum_landing_weight_baitboat = c(NA, NA, NA, 32.6, 20, NA, NA, 3, NA, NA,
    NA, NA, NA, NA, NA, NA, NA, NA, NA)), row.names = c(NA, -19L), class = "data.frame"))
})

