# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_weigh_catch_well_control.R

test_that("Doctest: logbook_weigh_catch_well_control", {
  # Created from @doctest for `logbook_weigh_catch_well_control`
  # Source file: R/logbook_weigh_catch_well_control.R
  # Source line: 28
  dataframe1 <- data.frame(catch_id = c("1", "2", "3", "4", "5", "6"), catch_weight = c(3, 2, 4, 1, 15, 6), speciesfate_code = c("6", "6", "6", "11", "6", "6"),
  species_fao_code = c("YFT", "SKJ", "FRI", "JOS", "ALB", "FRI"), activity_id = c("1", "1", "1", "1", "2", "3"))
  dataframe2 <- data.frame(wellactivityspecies_id = c("1", "2", "3", "4", "5"), wellactivityspecies_weight = c(3, 2, 4, 13, 4), species_fao_code = c("YFT", "SKJ", "XXX*",
    "ALB", "BET"), activity_id = c("1", "1", "1", "2", "4"))
  expect_equal(logbook_weigh_catch_well_control(dataframe1, dataframe2, output = "report"), structure(list(activity_id = c("1", "3", "2", "4"), logical = c(TRUE, FALSE, FALSE,
    FALSE), `ALB catch` = c(NA, NA, 15, NA), `ALB well` = c(NA, NA, 13, NA), `BET catch` = c(NA, NA, NA, NA), `BET well` = c(NA, NA, NA, 4), `SKJ catch` = c(2, NA, NA, NA),
  `SKJ well` = c(2, NA, NA, NA), `YFT catch` = c(3, NA, NA, NA), `YFT well` = c(3, NA, NA, NA), `XXX* catch` = c(4, 6, NA, NA), `XXX* well` = c(4, NA, NA, NA)), row.names = c(
    NA, -4L), class = c("tbl_df", "tbl", "data.frame")))
})

