# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_vessel_activity_object_operation_control.R

test_that("Doctest: logbook_vessel_activity_object_operation_control", {
  # Created from @doctest for `logbook_vessel_activity_object_operation_control`
  # Source file: R/logbook_vessel_activity_object_operation_control.R
  # Source line: 21
  dataframe1 <- data.frame(activity_id = c("1", "2", "3", "4", "5"), vesselactivity_code = c("6", "1", "6", NA, "6"))
  dataframe2 <- data.frame(floatingobject_id = c("1", "2", "3", "4"), objectoperation_code = c("2", "1", "1", NA),
  activity_id = c("1", "2", "3", "5"))
  expect_equal(logbook_vessel_activity_object_operation_control(dataframe1, dataframe2, output = "report"), structure(
    list(activity_id = c("1", "2", "3", "4", "5"), vesselactivity_code = c("6", "1", "6", NA, "6"), logical = c(TRUE,
      TRUE, FALSE, FALSE, FALSE)), row.names = c(NA, 5L), class = "data.frame"))
})

