# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_fishing_context_control.R

test_that("Doctest: logbook_fishing_context_control", {
  # Created from @doctest for `logbook_fishing_context_control`
  # Source file: R/logbook_fishing_context_control.R
  # Source line: 24
  dataframe1 <- data.frame(activity_id = c("1", "2", "3", "4", "5", "6", "7"), schooltype_code = c("2", "1", "2", "1", NA, "0", "2"))
  dataframe2 <- data.frame(observedsystem_id = c("1", "2", "3", "4", "5"), activity_id = c("1", "2", "2", "3", "4"), schooltype_code = c("2", "2", "1", "1", "2"))
  expect_equal(logbook_fishing_context_control(dataframe1, dataframe2, output = "report"), structure(list(activity_id = c("1", "2", "3", "4", "5", "6", "7"),
  logical = c(TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE), schooltype_code = c("2", "1", "2", "1", NA, "0", "2"), association_object_count = c(0, 1, 1, 0, 0, 0, 0)),
  row.names = c(NA, 7L), class = "data.frame"))
})

