# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_super_sample_number_control.R

test_that("Doctest: logbook_super_sample_number_control", {
  # Created from @doctest for `logbook_super_sample_number_control`
  # Source file: R/logbook_super_sample_number_control.R
  # Source line: 21
  dataframe1 <- data.frame(sample_id = c("1", "2", "3", "4", "5", "6", "7", "8"), sample_supersample = c(FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE))
  dataframe2 <- data.frame(samplespecies_id = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"), samplespecies_subsamplenumber = c(0, 0, 1, 1,
    2, 1, 1, 1, 0, 1, 1, 1, 3), sample_id = c("1", "1", "2", "2", "2", "3", "4", "4", "6", "6", "7", "8", "8"))
  expect_equal(logbook_super_sample_number_control(dataframe1, dataframe2, output = "report"), structure(list(sample_id = c("1", "2", "3", "4", "5", "6", "7", "8"),
  logical = c(TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), sample_supersample = c(FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE),
  count_subsamplenumber_n0 = c(0L, 3L, 1L, 2L, NA, 1L, 1L, 2L), count_subsamplenumber_0 = c(2L, 0L, 0L, 0L, NA, 1L, 0L, 0L), count_subsamplenumber_1 = c(0L, 2L,
    1L, 2L, NA, 1L, 1L, 1L), count_subsamplenumber = c(1L, 2L, 1L, 1L, NA, 2L, 1L, 2L), count_subsamplenumber_ncontinuous = c(1L, 0L, 0L, 0L, NA, 0L, 0L, 1L)),
  row.names = c(NA, 8L), class = "data.frame"))
})

