# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_vessel_activity_floating_object_missing_buoy_control.R

test_that("Doctest: logbook_vessel_activity_floating_object_missing_buoy_control", {
  # Created from @doctest for `logbook_vessel_activity_floating_object_missing_buoy_control`
  # Source file: R/logbook_vessel_activity_floating_object_missing_buoy_control.R
  # Source line: 27
  dataframe1 <- data.frame(floatingobject_id = c("1", "2", "3", "4", "5"), activity_id = c("1", "2", "3", "3", "4"))
  dataframe2 <- data.frame(activity_id = c("1", "2", "3", "4"), vesselactivity_code = c("13", "1", "13", NA))
  dataframe3 <- data.frame(transmittingbuoy_id = c("1", "2"), floatingobject_id = c("1", "3"))
  expect_equal(logbook_vessel_activity_floating_object_missing_buoy_control(dataframe1, dataframe2, dataframe3, output = "report"), structure(list(
    floatingobject_id = c("1", "2", "3", "4", "5"), logical = c(TRUE, TRUE, TRUE, FALSE, FALSE), count_buoy = c(1, 0, 1, 0, 0), vesselactivity_code = c("13", "1",
      "13", "13", NA)), row.names = c(NA, 5L), class = "data.frame"))
})

