# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_sample_harbour_control.R

test_that("Doctest: logbook_sample_harbour_control", {
  # Created from @doctest for `logbook_sample_harbour_control`
  # Source file: R/logbook_sample_harbour_control.R
  # Source line: 21
  dataframe1 <- data.frame(sample_id = c("1", "2"), trip_id = c("1", "2"))
  dataframe2 <- data.frame(trip_id = c("1"), harbour_id_landing = c("1"), harbour_label_landing = c("harbour_1"))
  expect_equal(logbook_sample_harbour_control(dataframe1, dataframe2, output = "report"), structure(list(sample_id = c("1", "2"), logical = c(TRUE, FALSE),
  harbour_label_landing = c("harbour_1", NA)), row.names = 1:2, class = "data.frame"))
})

