# Generated by doctest: do not edit by hand
# Please edit file in R/function_reason_for_discard_unknown_control.R

test_that("Doctest: function_reason_for_discard_unknown_control", {
  # Created from @doctest for `function_reason_for_discard_unknown_control`
  # Source file: R/function_reason_for_discard_unknown_control.R
  # Source line: 16
  catch <- data.frame(catch_id = c("1", "2", "3", "4"), speciesfate_code = c("6", "4", "5", "14"), reasonfordiscard_code = c(NA, "1", NA, "99"))
  expect_equal(function_reason_for_discard_unknown_control(catch), structure(list(catch_id = c("1", "2", "3", "4"), speciesfate_code = c("6", "4", "5", "14"),
  reasonfordiscard_code = c(NA, "1", NA, "99"), logical = c(TRUE, TRUE, FALSE, FALSE)), class = "data.frame", row.names = c(NA, -4L)))
})

