# Generated by doctest: do not edit by hand
# Please edit file in R/check_sample_harbour_inspector.R

test_that("Doctest: check_sample_harbour_inspector", {
  # Created from @doctest for `check_sample_harbour_inspector`
  # Source file: R/check_sample_harbour_inspector.R
  # Source line: 21
  dataframe1 <- data.frame(sample_id = c("1", "2"), trip_id = c("1", "2"))
  dataframe2 <- data.frame(trip_id = c("1"), harbour_id_landing = c("1"), harbour_label_landing = c("harbour_1"))
  expect_equal(check_sample_harbour_inspector(dataframe1, dataframe2, output = "report"), structure(list(sample_id = c("1", "2"), logical = c(TRUE, FALSE),
  harbour_label_landing = c("harbour_1", NA)), row.names = 1:2, class = "data.frame"))
})

