# Generated by doctest: do not edit by hand
# Please edit file in R/check_landing_total_weight_inspector.R

test_that("Doctest: check_landing_total_weight_inspector", {
  # Created from @doctest for `check_landing_total_weight_inspector`
  # Source file: R/check_landing_total_weight_inspector.R
  # Source line: 22
  dataframe1 <- data.frame(trip_id = c("1", "2", "3", "4", "5"), trip_landingtotalweight = c(10, 15, NA, 0, 4))
  dataframe2 <- data.frame(landing_id = c("1", "2", "3", "4", "5", "6"), landing_weight = c(4, 6, 10, 6, 2, NA), trip_id = c("1", "1", "2", "2", "3", "4"))
  expect_equal(check_landing_total_weight_inspector(dataframe1, dataframe2, output = "report"), structure(list(trip_id = c("1", "2", "3", "4", "5"), logical = c(TRUE,
    FALSE, FALSE, TRUE, FALSE), trip_landingtotalweight = c(10, 15, NA, 0, 4), sum_weightlanding = c(10, 16, 2, NA, NA)), row.names = c(NA, 5L), class = "data.frame"))
})

