# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_trip_activity_control.R

test_that("Doctest: logbook_trip_activity_control", {
  # Created from @doctest for `logbook_trip_activity_control`
  # Source file: R/logbook_trip_activity_control.R
  # Source line: 19
  dataframe1 <- data.frame(trip_id = c("1", "2"))
  dataframe2 <- data.frame(trip_id = c("1"), activity_id = c("1"))
  expect_equal(logbook_trip_activity_control(dataframe1, dataframe2, output = "report"), structure(list(trip_id = c("1", "2"), logical = c(TRUE, FALSE)), row.names = c(NA,
    -2L), class = "data.frame"))
})

