# Generated by doctest: do not edit by hand
# Please edit file in R/check_temporal_limit_inspector.R

test_that("Doctest: check_temporal_limit_inspector", {
  # Created from @doctest for `check_temporal_limit_inspector`
  # Source file: R/check_temporal_limit_inspector.R
  # Source line: 22
  dataframe1 <- data.frame(trip_id = c("1", "2", "3", "4", "5", "6"), trip_startdate = as.Date(c("2020/01/01", "2020/01/01", NA, "2020/01/24", "2020/02/01", "2020/02/13")),
  trip_enddate = as.Date(c("2020/01/02", "2020/01/02", "2020/01/24", NA, "2020/02/03", "2020/02/14")))
  dataframe2 <- data.frame(route_id = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), activity_date = as.Date(c("2020/01/01", "2020/01/02",
    "2020/01/01", "2020/01/02", "2020/01/03", "2020/01/24", "2020/01/24", "2020/02/01", "2020/02/03", "2020/02/13", "2020/02/13", "2020/02/14")), trip_id = c("1", "1",
    "2", "2", "2", "3", "4", "5", "5", "6", "6", "6"))
  expect_equal(check_temporal_limit_inspector(dataframe1, dataframe2, output = "report"), list(structure(list(trip_id = c("1", "2", "3", "4", "5", "6"), logical = c(TRUE,
    FALSE, FALSE, FALSE, FALSE, FALSE)), row.names = c(NA, -6L), class = "data.frame"), structure(list(trip_id = c("1", "1", "2", "2", "2", "3", "4", "5", "5", "6", "6"),
  trip_startdate = structure(c(18262, 18262, 18262, 18262, 18262, NA, 18285, 18293, 18293, 18305, 18305), class = "Date"), trip_enddate = structure(c(18263, 18263, 18263,
    18263, 18263, 18285, NA, 18295, 18295, 18306, 18306), class = "Date"), activity_date = structure(c(18262, 18263, 18262, 18263, 18264, 18285, 18285, 18293, 18295,
    18305, 18306), class = "Date"), inter_activity_date = c(TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE), exter_activity_date = c(FALSE, FALSE,
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), count_freq = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L), logical = c(TRUE, TRUE, TRUE, TRUE, FALSE,
    FALSE, FALSE, TRUE, TRUE, FALSE, TRUE)), row.names = c(NA, -11L), class = "data.frame")))
})

