# Generated by doctest: do not edit by hand
# Please edit file in R/check_weighting_sample_inspector.R

test_that("Doctest: check_weighting_sample_inspector", {
  # Created from @doctest for `check_weighting_sample_inspector`
  # Source file: R/check_weighting_sample_inspector.R
  # Source line: 32
  dataframe1 <- data.frame(activity_id = c("1", "2", "3", "4", "5"))
  dataframe2 <- data.frame(catch_id = c("1", "2", "3", "4", "5", "6"), catch_weight = c(4, 2, 5, 10, 3, 8), speciesfate_code = c("6", "6", "6", "6", "6", "6"),
  species_fao_code = c("YFT", "JOS", "ALB", "YFT", "YFT", "FRI"), activity_id = c("1", "1", "1", "2", "2", "5"))
  dataframe3 <- data.frame(sampleactivity_id = c("1", "2", "3", "4", "5"), sampleactivity_weightedweight = c(3, 6, 12.5, NA, 26), activity_id = c("1", "1", "2", "3", "4"))
  expect_equal(check_weighting_sample_inspector(dataframe1, dataframe2, dataframe3, output = "report"), structure(list(activity_id = c("1", "2", "3", "4", "5"), logical = c(
    TRUE, FALSE, TRUE, FALSE, TRUE), weight = c(9, 13, NA, NA, 8), weightedweight = c(9, 12.5, 0, 26, NA)), row.names = c(NA, 5L), class = "data.frame"))
})

