# Generated by doctest: do not edit by hand
# Please edit file in R/obs_catch_or_sample_outliers_control.R

test_that("Doctest: obs_catch_or_sample_outliers_control", {
  # Created from @doctest for `obs_catch_or_sample_outliers_control`
  # Source file: R/obs_catch_or_sample_outliers_control.R
  # Source line: 27
  catch <- data.frame(catch_id = c("1", "2", "3", "4"), catch_meanlength = c(30, 12, 59, 30),
  catch_meanlengthcomputedsource = c(NA_integer_, NA_integer_, NA_integer_, NA_integer_), species_minlength = c(10, 10, 10,
    NA), species_maxlength = c(60, 60, 60, NA))
  expect_equal(obs_catch_or_sample_outliers_control(catch), structure(list(catch_id = c("1", "2", "3", "4"), length = c(30,
    12, 59, 30), species_minlength = c(10, 10, 10, NA), species_maxlength = c(60, 60, 60, NA), logical = c(TRUE, FALSE,
    FALSE, FALSE)), class = "data.frame", row.names = c(NA, -4L)))
})

