# Generated by doctest: do not edit by hand
# Please edit file in R/obs_sample_sex_control.R

test_that("Doctest: obs_sample_sex_control", {
  # Created from @doctest for `obs_sample_sex_control`
  # Source file: R/obs_sample_sex_control.R
  # Source line: 17
  sample <- data.frame(samplemeasure_id = c("1", "2", "3", "4"), sex_label = c(
    NA, "Female", "Female", "Male"), species_faocode = c("CNT", "DOL", "FAL",
    "CNT"), speciesgroup_label = c("Other bony fishes", "Other bony fishes",
    "Sharks", "Other bony fishes"))
  expect_equal(obs_sample_sex_control(sample), structure(list(samplemeasure_id = c(
    "1", "2", "3", "4"), sex_label = c(NA, "Female", "Female", "Male"),
  species_faocode = c("CNT", "DOL", "FAL", "CNT"), speciesgroup_label = c(
    "Other bony fishes", "Other bony fishes", "Sharks", "Other bony fishes"),
  logical = c(TRUE, TRUE, TRUE, FALSE)), class = "data.frame", row.names = c(NA,
    -4L)))
})

