# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_length_class_control.R

test_that("Doctest: logbook_length_class_control", {
  # Created from @doctest for `logbook_length_class_control`
  # Source file: R/logbook_length_class_control.R
  # Source line: 19
  dataframe1 <- data.frame(samplespeciesmeasure_id = c("1", "2", "3", "4", "5"), species_fao_code = c("YFT", "YFT", "LTA", "YFT", "YFT"), sizemeasuretype_code = c("FL", "PD1",
    "FL", "FL", "FL"), samplespeciesmeasure_sizeclass = c(10, 90, 85, 83, NA))
  expect_equal(logbook_length_class_control(dataframe1, output = "report"), structure(list(samplespeciesmeasure_id = c("1", "2", "3", "4", "5"), logical = c(TRUE, TRUE, TRUE,
    FALSE, FALSE), samplespeciesmeasure_sizeclass = c(10, 90, 85, 83, NA)), row.names = c(NA, 5L), class = "data.frame"))
})

