# Generated by doctest: do not edit by hand
# Please edit file in R/check_measure_inspector.R

test_that("Doctest: check_measure_inspector", {
  # Created from @doctest for `check_measure_inspector`
  # Source file: R/check_measure_inspector.R
  # Source line: 22
  dataframe1 <- data.frame(samplespecies_id = c("1", "2", "3", "4", "5", "6"), samplespecies_measuredcount = c(4, 6, 15, 6, 7, NA), sample_id = c("1", "1", "2", "3", "4",
    "5"))
  dataframe2 <- data.frame(samplespeciesmeasure_id = c("1", "2", "3", "4", "5", "6"), samplespeciesmeasure_count = c(10, 10, 5, 3, 2, 8), samplespecies_id = c("1", "3",
    "3", "4", "4", "6"))
  expect_equal(check_measure_inspector(dataframe1, dataframe2, output = "report"), structure(list(sample_id = c("1", "2", "3", "4", "5"), logical = c(TRUE, TRUE, FALSE,
    FALSE, FALSE), sum_measuredcount = c(10, 15, 6, 7, NA), sum_count = c(10, 15, 5, NA, 8)), row.names = c(NA, -5L), class = "data.frame"))
})

