# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_floating_object_part_DFAD_when_leaving_control.R

test_that("Doctest: logbook_floating_object_part_DFAD_when_leaving_control", {
  # Created from @doctest for `logbook_floating_object_part_DFAD_when_leaving_control`
  # Source file: R/logbook_floating_object_part_DFAD_when_leaving_control.R
  # Source line: 21
  dataframe1 <- data.frame(floatingobject_id = c("1", "2", "3", "4", "5", "6"), objectoperation_code = c("2", "1", "1", "1", "1", "1"))
  dataframe2 <- data.frame(floatingobjectpart_id = c("1", "2", "3", "4", "5", "6"), objectmaterial_code = c("2-1", "1-1-1", "1-1", "1-1-1", "1-1-2", "2-1"),
  floatingobjectpart_whenleaving = c("true", "true", "true", "false", NA, "true"), floatingobject_id = c("1", "2", "3", "4", "4", "5"))
  expect_equal(logbook_floating_object_part_DFAD_when_leaving_control(dataframe1, dataframe2, output = "report"), structure(list(floatingobject_id = c("1", "2", "3", "4", "5",
    "6"), objectoperation_code = c("2", "1", "1", "1", "1", "1"), logical = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)), row.names = c(NA, 6L), class = "data.frame"))
})

