# Generated by doctest: do not edit by hand
# Please edit file in R/logbook_position_control.R

test_that("Doctest: logbook_position_control", {
  # Created from @doctest for `logbook_position_control`
  # Source file: R/logbook_position_control.R
  # Source line: 33
  dataframe1 <- data.frame(activity_id = c("1", "2", "3", "4", "5", "6", "7"), ocean_label = c("ocean_1", "ocean_2", "ocean_2", "ocean_2", "ocean_2", "ocean_1", NA),
  activity_position = c("POINT (0 0)", "POINT (0 0)", "POINT (-1 -1)", "POINT (1 1)", "POINT (3 3)", NA, "POINT (1 1)"), trip_id = c("1", "2", "2", "2", "2", "2", "2"))
  dataframe2 <- data.frame(trip_id = c("1", "2"), harbour_position_departure = c("POINT (20 20)", "POINT (-1.05 -1)"), harbour_position_landing = c("POINT (20 20)",
    "POINT (20 20)"))
  dataframe3 <- sf::st_sf(data.frame(ID = c("ocean_1", "ocean_2"), geometry = sf::st_sfc(sf::st_polygon(list(rbind(c(0, 0), c(2, 0), c(2, 2), c(0, 2), c(0, 0)))), sf::st_polygon(
    list(rbind(c(0, 1), c(3, 1), c(3, 2), c(0, 2), c(0, 1)))), crs = 4326)))
  expect_equal(logbook_position_control(dataframe1, dataframe2, dataframe3, output = "report"), list(structure(list(activity_id = c("1", "2", "3", "4", "5", "6", "7"),
  logical = c(TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE), type = c("Sea", "Sea", "Harbour", "Sea", "Excluding shapes oceans", "No position", "Sea"), ocean_label = c(
    "ocean_1", "ocean_2", "ocean_2", "ocean_2", "ocean_2", "ocean_1", NA), ocean_calculate = c("ocean_1", "ocean_1", NA, "ocean_1 ocean_2", NA, NA, "ocean_1 ocean_2")),
  row.names = c(NA, 7L), class = "data.frame"), structure(list(activity_id = c("1", "2", "3", "4", "5", "6", "7"), activity_position = c("POINT (0 0)", "POINT (0 0)",
    "POINT (-1 -1)", "POINT (1 1)", "POINT (3 3)", NA, "POINT (1 1)"), logical_harbour = c(FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE), logical_ocean = c(TRUE, FALSE,
    FALSE, TRUE, FALSE, FALSE, FALSE), logical = c(TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE), type = c("Sea", "Sea", "Harbour", "Sea", "Excluding shapes oceans",
    "No position", "Sea"), ocean_label = c("ocean_1", "ocean_2", "ocean_2", "ocean_2", "ocean_2", "ocean_1", NA), ocean_calculate = c("ocean_1", "ocean_1", NA,
    "ocean_1 ocean_2", NA, NA, "ocean_1 ocean_2"), activity_crs = c(4326, 4326, 4326, 4326, 4326, 4326, 4326)), row.names = c(NA, 7L), class = "data.frame")))
})

